# Harbor drone integration.
---
clone:
  path: github.com/vmware/harbor
  tags: true

build:
  vicui:
    image: $${TEST_BUILD_IMAGE=gcr.io/eminent-nation-87317/vic-integration-test:1.26}
    pull: true
    environment:
      BIN: bin
    commands:
      - make mark
      - make vic-ui-plugins
      - make sincemark
    when:
      success: true
