# Harbor drone integration.
---
clone:
  path: github.com/vmware/harbor
  tags: true

build:
  harbor:
    image: gcr.io/eminent-nation-87317/vic-integration-test:1.26
    pull: true
    environment:
      BIN: bin
    commands:
      - make install -e DEVFLAG=true
    when:
      success: true
